pip install requests
pip install pycryptodome
pip install pystyle
pip install colorama
pip install auto_py_to_exe
pip install pyinstaller
pip install wmi
pip install customtkinter
pip install cryptography
